### ISSUE TITLE
<li>Collapses on IE11

### ISSUE THREAD

**Issue by lewisik** [AWulkan/FlexNav#2]
Hi,
Thankyou for sharing your work!
I found `<li>` part collapses on IE11, its width terribly shrinks.

I could get away with it by simply adding 

`.nav-link { flex-basis:auto; }`

to css.

Thanks

**Comment by awulkan** [comment]
Thank you I will look into that. :)

This is a project that I created while learning flexbox a long time ago. I never thought anyone would ever find it useful, but I guess I was wrong. Someday I will rewrite this whole navigation bar.

**Comment by awulkan** [comment]
Thank you, I have now added your solution to the code. :)
